# fly.toml app configuration file generated for smsparse on 2023-08-28T18:53:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smsparse"
primary_region = "sin"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
